name: WF Run
on:
  workflow_run:
    workflows: ["WF Precondition"]
    types:
      - completed

jobs:
  echo:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Show test.txt
        run: cat "test.txt"
