name: Released

on:
  release:
    types:
      - released
      - prereleased

env:
  TAG: ${{ github.event.release.tag_name }}

jobs:
  check_tag:
    runs-on: ubuntu-latest
    outputs:
      do_release: ${{ steps.check_tag.outputs.do_release }}
    steps:
      - name: check tag ${{ github.ref }}
        id: check_tag
        run: |
          if [[${{ github.ref }} =~ refs\/tags\/[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "::set-output name=do_release::true"
          else
            echo "::set-output name=do_release::false"
          fi

  on-release:
    runs-on: ubuntu-latest
    needs: [check_tag]
    if: needs.check_tag.outputs.do_release == 'true'
    steps:
      - run: echo "Releasing ${TAG}"