name: WF Precondition
on:
  - push

jobs:
  echo:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Show test.txt
        run: cat "test.txt"
